server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  # 解决springboot 数据源循环依赖问题 eureka服务无法被调用
  cloud:
    refresh:
      refreshable: none
  rabbitmq:
    addresses: 192.168.8.6
    username: leyou
    password: leyou
    virtual-host: leyou
    template:
      exchange: leyou.item.exchange
    publisher-confirms: true
logging:
  level:
    cup.com.mapper: DEBUG
# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

# actuator监控应用
management:
  endpoints:
    info:
      build:
        enabled: true
    web:
      exposure:
        #暴露所有节点
        include: "*"
    health:
      #关闭过滤敏感信息
      sensitive: false
  endpoint:
    health:
      #显示详细信息
      show-details: ALWAYS




