# 端口号
server:
  port: 10086
  max-http-header-size: 20480
# 服务名称
spring:
  application:
    name: leyou-registry
# 单个eureka的情况
eureka:
  client:
    # 不用拉取服务
    fetch-registry: false
    # 不用在eureka中注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
  # 开发阶段使用，上线需删掉
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 每隔5秒进行一次服务列表清理
    eviction-interval-timer-in-ms: 2000000
  instance:
    prefer-ip-address: true
    instance-id: http://127.0.0.1:${server.port}/eureka
