server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.8.6
    username: leyou
    password: leyou
    virtual-host: leyou
    template:
      exchange: leyou.item.exchange
  redis:
    host: 192.168.8.6
    database: 0
    port: 6379
    timeout: 1000
# 阿里短信配置
leyou:
  sms:
    accessKeyId: LTAIaaiu7S1tYB8KV6                    # 你自己的accessKeyId
    accessKeySecret: rpu9911duohLQ11Fl5CtOQnMGyMnL708wS  # 你自己的AccessKeySecret
    signName: 心飞为你飞                              # 签名名称
    verifyCodeTemplate: SMS_76525096                 # 模板名称